name: rocm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.12.2=h06a4308_0
  - cffi=2.0.0=py311h4eded50_1
  - cmake=4.1.2=hc946e07_0
  - expat=2.7.3=h7354ed3_4
  - gettext=0.21.0=hedfda30_2
  - icu=73.1=h6a678d5_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jansson=2.14=h5eee18b_1
  - ld_impl_linux-64=2.44=h153f514_2
  - libcurl=8.16.0=heebcbe5_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libnghttp2=1.67.1=h697f920_0
  - libnsl=2.0.0=h5eee18b_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2025.0.0=hacee8c2_941
  - mkl-include=2025.0.0=hc79277c_941
  - mkl-service=2.5.2=py311hacdc0fc_0
  - mkl_fft=2.1.1=py311h8fe796d_0
  - mkl_random=1.3.0=py311h505adc9_0
  - ncurses=6.5=h7934f7d_0
  - ninja=1.13.1=h06a4308_0
  - ninja-base=1.13.1=h0f57076_0
  - numpy=2.3.5=py311h08c6c3d_0
  - numpy-base=2.3.5=py311h00548fb_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.23=py311h06a4308_0
  - python=3.11.14=h6fa692b_0
  - pyyaml=6.0.3=py311h591646f_0
  - readline=8.3=hc2a1206_0
  - rhash=1.4.6=hd199180_1
  - setuptools=80.9.0=py311h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - tk=8.6.15=h54e0aa7_0
  - typing_extensions=4.15.0=py311h06a4308_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.12.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - backcall==0.2.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.4.1
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.4.0
      - docopt==0.6.2
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.9
      - loguru==0.7.3
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.5
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==11.3.0
      - pipreqs==0.5.0
      - platformdirs==4.5.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytorch-triton-rocm==3.0.0
      - pytz==2025.2
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - six==1.17.0
      - soupsieve==2.8
      - stack-data==0.6.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - torch==2.4.1+rocm6.0
      - torchaudio==2.4.1+rocm6.0
      - torchvision==0.19.1+rocm6.0
      - tornado==6.5.3
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.3
      - tzdata==2025.2
      - urllib3==2.6.2
      - wcwidth==0.2.14
      - webencodings==0.5.1
      - xxhash==3.6.0
      - yarg==0.1.9
      - yarl==1.22.0
prefix: /home/yopparay/miniconda3/envs/rocm
